import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>devter 🐤</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <a href="https://nextjs.org">devter</a>
        </h1>
        <nav>
          <Link href="/timeline">timeline</Link>
        </nav>
      </main>
    </>
  );
}
